version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - server
    depends_on:
      - auth
      - chat1
      - chat2

  auth:
    image: parkgw9071/auth
    container_name: auth
    restart: always
    networks:
      - server
    expose:
      - "8080"

  chat1:
    image: parkgw9071/chat
    container_name: chat1
    restart: always
    networks:
      - server
    expose:
      - "8080"

  chat2:
    image: parkgw9071/chat
    container_name: chat2
    restart: always
    networks:
      - server
    expose:
      - "8080"

networks:
  server:
    external: true
