CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS chat;

CREATE USER 'user'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON auth.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON chat.* TO 'user'@'%';

FLUSH PRIVILEGES;